services:
  test-db:
    image: postgres:15-alpine 
    container_name: go-app-test-db 
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testapp_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testapp_db"]
      interval: 5s  
      timeout: 5s  
      retries: 5  
